### PR TITLE
Add SERIES-RELEASE specific channel maps

### PR DESCRIPTION
**Pull request by nicolasbock**
The charmhub introduced charm channels that are not simply OS series specific
but also depend on the OpenStack release. This change adds SERIES-RELEASE
specific maps.

Closes: canonical/stsstack-bundles#42
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

### CODE REVIEW

**Comment by nicolasbock** [comment]
I have tested a few combinations of series and release and they all worked @dosaboy .

**Review by dosaboy — CHANGES_REQUESTED** [review]
as discussed

**Comment by nicolasbock** [comment]
I have updated the maps @dosaboy and also included a script to test the channel map. For example:

```console
$ ./common/ch_channel_map/test-channel-map.sh focal ussuri
hacluster              2.0.3/edge
mysql-router           8.0/edge
mysql-innodb-cluster   8.0/edge
ovn-central            20.03/edge
ovn-chassis            20.03/edge
ovn-dedicated-chassis  20.03/edge
percona-cluster        unset
rabbitmq-server        3.8/edge
vault                  1.6/edge
```

Also note the layering of `focal-wallaby` for example. It's basically the same as `focal-ussuri` but the `ovn` components are slightly different.

**Review by dosaboy — APPROVED** [review]
lgtm!

**Pull request merged**
