### PR TITLE
Fix ha overlays

### PR DESCRIPTION
**Pull request by tpsilva**
vip_iface is not being set, so it defaults to eth0, which fails on all ha openstack deployments. Setting it to default to ens3 fixes that.

### CODE REVIEW

**Comment by dosaboy** [comment]
this has never failed for me fwiw, i wonder why

**Comment by nicolasbock** [comment]
What OS series did you use @tpsilva?

**Comment by nicolasbock** [comment]
I cannot reproduce with
```console
./generate-bundle.sh --release ussuri --ovn --ha
```
Am I missing something?

**Comment by nicolasbock** [comment]
You have more than `10.5.0.0/16` alpha space?

**Comment by tpsilva** [comment]
Yes, I had another subnet that I added to reproduce a Juju issue. Removing that subnet fixed the HA issue...

**Pull request closed without merging**
